### ISSUE TITLE
Need to look into the Data Set download function

### ISSUE THREAD

**Issue by selrashidi** [layersoflondon/application#118]

**Comment by Forester1** [comment]
There are a lot of things to consider here but if we take it as that the datasets on the Layers of London website are a collection of data on a topic, with shared metadata (licence, description, modified date, owner, copyright, etc.) that also allows users to filter a dataset to find the data they want. The data will be stored in datasets which contain related data issued under a shared usage licence (each with its own metadata), along with vocabularies of supporting terms. For instance for the LMA data, we will be using the UKAT standard http://www.ukat.org.uk/about/.

Most datasets on the site will have an API function (licence permitting) which includes details of how to access the data programmatically so that the data catalogue and data can be discovered and used by others (third party websites, apps, online databases, GIS, data visualisations). I have outlined some of the most popular sites and technologies for creating data catalogues as examples below:

- Data.gov.uk https://data.gov.uk/dataset/82dfc1ce-2bdd-4e94-9543-eec948ea0a1f/os-open-map-local
- OS OpenData-Mapping data and geographic information from OS https://www.ordnancesurvey.co.uk/opendatadownload/products.html
- National Library of Scotland | Maps http://maps.nls.uk/geo/find/#zoom=15&lat=51.5151&lon=-0.0933&layers=102&b=1&point=51.5154,-0.0930
- Cambridgeshire Insight Open Data http://opendata.cambridgeshireinsight.org.uk/dataset?query=&sort_bef_combine=changed+DESC (Made using DKAN)
- Data Mill North – Open Data for the North of England https://datamillnorth.org/dataset?topics=8529d478-f9ba-11e4-8954-08002750a12e (Made using DataPress)
- Open Barnet https://open.barnet.gov.uk/dataset (Made using Datapress)
- Linked Data from The Open University http://data.open.ac.uk/ (Linked Data)
- UK Ministry of Housing, Communities and Local Government linked data platform http://opendatacommunities.org/data (Linked Data)
-  

To start with, unless there is already a solution at hand, we need to see what is available on data catalogues for downloads and ideally keep it simple to enable the functionality to be developed in time with the other functions and timescales.

This is related to the following tickets:

- Theme/types tagging of records #113
- Being able to export data (and datasets) #119
- Administrator level dataset upload for new records #89

**Comment by Forester1** [comment]
Quick question. @edtjones @phendrick Is there a wireframe available for this?

**Comment by edtjones** [comment]
haven't wireframed this @Forester1 - ideas welcome

**Comment by Forester1** [comment]
@edtjones pls see first stab at version 1 

[Download_Wireframe_v0.1.pdf](https://github.com/layersoflondon/application/files/2210117/Download_Wireframe_v0.1.pdf)

fyi @selrashidi @KFlynn1 @amytodd
