### ISSUE TITLE
Requirement to disable 'save image as' option on right click for certain content?

### ISSUE THREAD

**Issue by Forester1** [layersoflondon/application#123]
There is a requirement to prevent users from right-clicking on image on the site and saving them for certain collections. 

Can certain images, that publishers will select in the upload process, be uses as a background-image of a div element. Or is there another easier way to do this?

@selrashidi

**Comment by Forester1** [comment]
Hi

The concern is unregistered users will be able to ‘right click’ and download images, without registering. The preference for some content suppliers is the comfort in the knowledge that download rights be reserved for registered users only. 
Is there a way we can implement a setting on the 'Save as' on the bulk uploading of content, rather than the individual upload, to have such a restriction?

**Comment by edtjones** [comment]
The problem is that it's literally impossible to stop someone copying an image they have on their screen. It's a fundamental problem that you're trying to stop them saving something they already have in their posession. Suppressing right-click options is notionally possible, but it wouldn't stop someone who wanted to do it, and it's pretty bad user experience to interfere with the right-click options on a web page (plugins often add or amend options, and invoking your own right-click handler means that these wouldn't be visible).

Either we need to limit who can see these records ('you need to log in to see this - create an account now') or the publisher needs to understand that these are going to be visible and potentially downloadable.

Does this relate to #103 and watermarking?
