### ISSUE TITLE
Viewing a collection: Implement a big edit button

### ISSUE THREAD

**Issue by selrashidi** [layersoflondon/application#211]
Assuming I decide to create a collection, and when I get to the create collection page decide that I am going to create a team to work on my collection as well, how can I create a team easily?

**Comment by andyError** [comment]
I think it's fine that there is a separation between these functions. However, you must be able to easily create one, then easily create the other, then easily join them. I think the current UX falls down a bit, because it's hard to get back to your newly created collection in order to assign it to the team - but I think this would be solved by including collections in 'Your content' and having an obvious EDIT button.

I'm going to retitle this issue to cover that ^
