### ISSUE TITLE
The 'Add A Record' form says 'Edit a Record' rather than 'Add a Record'

### ISSUE THREAD

**Issue by selrashidi** [layersoflondon/application#371]
![image](https://user-images.githubusercontent.com/22592196/45367034-3580d880-b5d8-11e8-9f17-9048442187de.png)

**Comment by edtjones** [comment]
Will make it say something generic. The problem is that technically you are editing at that point because we save the record as soon as you open the form (to allow you to start adding attachments etc without entering a title, should you wish). Let's call it "Add your record" until they enter a title, and then call it "Your record: [title name]" ?

**Comment by selrashidi** [comment]
Sounds good Ed.






________________________________
