### ISSUE TITLE
The inner workings of search

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#629]
On the map layers page, the search function does not always seem to work well. For example, when we searched for "Booth" and Hornsey, nothing came up.

**Comment by edtjones** [comment]
I have investigated this; at the moment on staging the phrase `booth hornsey` returns booth and hornsey maps.

![Screen Shot 2020-04-02 at 20 39 51](https://user-images.githubusercontent.com/4377783/78294363-319e0980-7522-11ea-8724-842210b06aad.jpg)

I'm quite sure there's tuning to be done here but we need more information about what's wrong in order to make it better. (sorry)

**Comment by mpdavies** [comment]
OK, if we do not migrate to HUMAP then we need to review the search and do what we can to improve it within the constraints. I think there were some improvements made since this issue was raised?

**Comment by edtjones** [comment]
Lots of changes have been made since this ticket was opened which I think has helped substantially. I'm closing this ticket; we can revisit to make sure the UX in humap is better.
