### ISSUE TITLE
Change media breakpoints use desktop site on smaller screens

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#632]
For Andy to spend 30 mins investigating this
 
The site layout and behaviour is based solely on the size the page is rendered at - which is a common approach for progressive web apps like this. The screenshots appear to be on a small screen, this could be because of the physical size of the machine, the user's display settings, or the users browser zoom settings - but at this size the site is displaying in what you could fairly call 'tablet mode'. This may not feel totally ideal BUT the site should function perfectly well in this mode - it is designed to do so at that size. In this instance: the user here could zoom out (CMD + minus), which would render the document wider and thus the site would appear in 'desktop mode' - but I wouldn't necessarily expect users to know to do that.

It's possible to set the breakpoints between tablet and desktop layouts as we see fit, but it would require a lot of effort and testing to change them at this point - and I wouldn't suggest that that would be a good use of resources.

**Comment by andyError** [comment]
Just a note for me: screen width in question is 1024 pixels.

**Comment by andyError** [comment]
I've had a look into this, essentially what is being asked is:

_Can we use the desktop version of the site on smaller screens?_

Specifically, down to 1024 pixels wide, which is the width of -client's- -laptop-. The answer is that we can and technically I think it's a little simpler than I thought. However, from a user experience point of view, this will require some changes - and doing this throws up the possibility for a lot new bugs and issues - worrying because we'll be making such drastic changes late in the project. Having given the site a quick look over, there are some key things which will need immediately addressing.

For example, for the tray to work in such a small area we will need to adjust the spacing of the records and maybe the font sizes of the text:

![Screenshot 2020-04-29 at 15 49 33](https://user-images.githubusercontent.com/5146825/80611594-b0f3ff80-8a32-11ea-8812-3c9cbf90d129.jpg)

…and for another example, the sidebar icons do not have enough vertical space at this size, so we would have to change the spacing/size of them.

![Screenshot 2020-04-29 at 15 49 15](https://user-images.githubusercontent.com/5146825/80611755-f0bae700-8a32-11ea-9753-7af327e6b09b.jpg)

These changes will take about a days effort.

**Comment by mpdavies** [comment]
not clear if these changes were made or not? Probably another issue that needs to be borne in mind re. HUMAP if not solved by that already?

**Comment by edtjones** [comment]
We did deploy these changes. Closing.
