### ISSUE TITLE
Date on new records

### ISSUE THREAD

**Issue by EliWei** [layersoflondon/application#643]
When creating a new record, if you don't fill in the date first the exclamation mark correctly comes up. However, if you then go to fill the date in, sometimes the exclamation mark realises it needs to disappear now, but then takes with it some of the numbers you've entered, causing something like 1873 to suddenly become 173.

Also: 
Adding an end date is temperamental - A volunteer reported that she'd been having problems adding dates. When typing dates in they would change for no apparent reason. I've just tried myself and for the end date, when typing in the day, when i was typing in 1, it suddenly changing to a 3.
Also when I was typing in the year it happened, I was writing 2020 and after tying in the first 0, the red "!" disappeared (as described in the previous email) ending up with 220.

**Comment by EliWei** [comment]
I have a video of this happening

**Comment by edtjones** [comment]
I THINK we have resolved this.

**Comment by mpdavies** [comment]
does that mean it is fixed or that it won't be fixed?

**Comment by edtjones** [comment]
So, we've done a lot of work on the date input stuff (we need to account for people who only want to enter a year, and we have to store a whole date and fill in the gaps, while keeping track of which portion of the date has been filled in by us). I think what's being described above is now resolved, so I'm going to close this issue. I marked it as 'won't fix' because in any case, the effort required to do more work on this vs the edge-case problem we may not have accounted for won't be worth it. (we will be building this from scratch for Humap, and will take into account the complexities in the technical design from the start)
